### ISSUE TITLE
Suggestion: Webhooks & Monitor Mode

### ISSUE THREAD

**Issue by ItsCEED** [andy-zhangief/binance-bot#3]
The idea is following:
Scan for PrePumps/Pumps and once detected send message to discord webhook or any other webhook.

The idea is for monitoring purposes

**Comment by andy-zhangief** [comment]
Sorry, but I'm not really interested in anything discord related. Feel free to fork my project and implement for yourself :)

**Comment by andy-zhangief** [comment]
Also, I just added a detection mode so you have a very clean entry point if you do choose to fork it. Just use argument `--detect`
