### ISSUE TITLE
error auto mode

### ISSUE THREAD

**Issue by awee1233** [andy-zhangief/binance-bot#4]
PNL: 0, ONTBTC, AUTO, Current: 0.0000246, Buy Window: N/A, Opportunity Expires: 0 GATHERING DATA
last price for ONTBTC is : 0
Buying NaN ONT
PUMP ERROR: {"code":-1100,"msg":"Illegal characters found in parameter 'quantity'; legal range is '^([0-9]{1,20})(\\.[0-9]{1,20})?$'."}
PS C:\Users\Admin\Downloads\binance-bot-main>

how to fix this error?

**Comment by andy-zhangief** [comment]
What did you type to execute the program? Did you set up your API keys properly? It looks like it couldn't fetch the price of the coin.

**Comment by awee1233** [comment]
node main ONTBTC

API has been entered correctly
// rename to secrets.js
module.exports = {
API_KEY: "xxxxxpkqtuC5vWLaTbi",
API_SECRET: "xxxxxqPp9mbuPXwJbqjOnwjPmnvgzpWCugTT"
}

**Comment by andy-zhangief** [comment]
hit me up on discord and I'll help. Link in the readme
